# -*- coding: utf-8 -*-
"""image enhancement

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ugSlYK1t0nY441nQL5xm0sxAYkBRvRub
"""

import numpy as np

import cv2

from google.colab.patches import cv2_imshow
image=cv2.imread("/content/ronaldo.jpeg",0)
cv2_imshow(image)

image.shape

dn=255-image

cv2_imshow(dn)

#THESHOLDING

threshold=128

for row in range(image.shape[0]):
    for col in range(image.shape[1]):
        if image[row, col] >= threshold:
            image[row, col] = 255
        else:
            # Set pixel to black (0)
            image[row, col] = 0
cv2_imshow(image)

#gray level slicing

lower=100
upper=150

from google.colab.patches import cv2_imshow
image=cv2.imread("/content/images (1).jpeg",0)
cv2_imshow(image)

for row in range(image.shape[0]):
    for col in range(image.shape[1]):
        if lower<image[row, col]<upper:
            image[row, col] = 255
        else:
            image[row,col] =image[row,col]
        

cv2_imshow(image)

from google.colab.patches import cv2_imshow
image=cv2.imread("/content/images (1).jpeg",0)
cv2_imshow(image)

background=0
upper=200
lower=50
for row in range(image.shape[0]):
    for col in range(image.shape[1]):
        if lower<=image[row, col]<=upper:
            image[row, col] = 255
        else:
            image[row,col]==background
        

cv2_imshow(image)