# -*- coding: utf-8 -*-
"""IPCV LAB 8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c5kBQIFmhRJ-tZ9nFV9TYLo3yDaRPKYE
"""

#low pass filter

import numpy as np
from scipy import fftpack
from scipy import ndimage
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
import cv2

img = cv2.imread('/content/WhatsApp Image 2023-04-09 at 10.54.13.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

fft = fftpack.fft2(gray)

shifted_fft = fftpack.fftshift(fft)

cutoff_frequency = 60
rows, cols = gray.shape
crow, ccol = rows//2, cols//2

mask = np.zeros((rows, cols))
for i in range(rows):
    for j in range(cols):
        if np.sqrt((i-crow)**2 + (j-ccol)**2) <= cutoff_frequency:
            mask[i,j] = 1

plt.imshow(mask, cmap='gray')
plt.title('Low Pass Filter Function')
plt.axis('off')
plt.show()

masked_fft = np.multiply(shifted_fft, mask)

unshifted_fft = fftpack.ifftshift(masked_fft)

filtered = fftpack.ifft2(unshifted_fft).real

filtered = cv2.convertScaleAbs(filtered)

cv2_imshow(img)
cv2_imshow(filtered)
cv2.waitKey(0)
cv2.destroyAllWindows()

#High Pass Filter

import numpy as np
from scipy import fftpack
from google.colab.patches import cv2_imshow
from scipy import ndimage
import matplotlib.pyplot as plt
import cv2
img = cv2.imread('/content/WhatsApp Image 2023-04-09 at 10.54.13.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
fft = fftpack.fft2(gray)

shifted_fft = fftpack.fftshift(fft)
cutoff_frequency = 60
rows, cols = gray.shape
crow, ccol = rows//2, cols//2
mask = np.ones((rows, cols))
for i in range(rows):
    for j in range(cols):
        if np.sqrt((i-crow)**2 + (j-ccol)**2) <= cutoff_frequency:
            mask[i,j] = 0

plt.imshow(mask, cmap='gray')
plt.title('High Pass Filter Function')
plt.axis('off')
plt.show()

masked_fft = np.multiply(shifted_fft, mask)
unshifted_fft = fftpack.ifftshift(masked_fft)

filtered = fftpack.ifft2(unshifted_fft).real

filtered = cv2.convertScaleAbs(filtered)

cv2_imshow(img)
cv2_imshow(filtered)
cv2.waitKey(0)
cv2.destroyAllWindows()

"""**CONCLUSION**-A high-pass filter allows high-frequency signals to pass through while attenuating low-frequency signals, while a low-pass filter allows low-frequency signals to pass through while attenuating high-frequency signals."""