# -*- coding: utf-8 -*-
"""ipcv lab1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15rXHUuAFWwWkvdqo0iVOxF8mEDpXPrbZ
"""

import cv2

import numpy as ap

image=cv2.imread("/content/WhatsApp Image 2023-05-13 at 15.43.12.jpg")

from google.colab.patches import cv2_imshow
cv2_imshow(image)

gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

cv2_imshow(gray)

crop=gray[40:200,10:330]

cv2_imshow(crop)

img=cv2.imread("/content/IPD_FLOW_CHART-Page-1.jpg")

cv2_imshow(img)

image.shape

img.shape

img=cv2.resize(img,(614,473))

img.shape

add=cv2.add(image,img)
cv2_imshow(add)

sub=cv2.subtract(image,img)

cv2_imshow(sub)

ad=cv2.bitwise_and(image,img)
cv2_imshow(ad)

oo=cv2.bitwise_or(image,img)
cv2_imshow(oo)

nooo=cv2.bitwise_not(image)
cv2_imshow(nooo)

xor=cv2.bitwise_xor(image,img)
cv2_imshow(xor)

