# -*- coding: utf-8 -*-
"""IPCV lab3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_fpKOjiXNuw8-Y7BwavTyR0vSa5T1L8
"""

import cv2
import numpy as np

from google.colab.patches import cv2_imshow
image=cv2.imread("/content/pan_card_stavan.jpeg",0)
cv2_imshow(image)

import matplotlib.pyplot as plt

def contrast_stretching(r,a,b,l,m,n):
  v=l*a
  w=m*(b-a)+v
  if r>0 and r<=a:
    return l*r
  elif a<r<=b:
    return m*(r-a)+v
  else:
    return m*(r-b)+w

height, width = image.shape
image1=np.zeros((height,width))
for i in range(height):
    for j in range(width):
        image1[i][j] = contrast_stretching(image[i][j],80,150,0.4,1.5,0.7)
cv2_imshow(image1)

#log transformation

c=6000000000000
op=c*np.log(image+1)
plt.imshow(op,cmap="gray")

#power transformation

gamma=1.5
op1=image**(gamma)
plt.imshow(op1,cmap="gray")

