# -*- coding: utf-8 -*-
"""IPCV LAB10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YBUtYXJJSm6oYHENZdESDyp2pt2dHL4k
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread('/content/download.png', cv2.IMREAD_GRAYSCALE)

image_gray = np.array(image)

prewitt_y = np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]])
prewitt_x = np.array([[-1, -1, -1], [0, 0, 0], [1, 1, 1]])

sobel_y = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
sobel_x = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])

def convolve(image, kernel):
    (iH, iW) = image.shape[:2]
    (kH, kW) = kernel.shape[:2]
    output = np.zeros((iH - kH + 1, iW - kW + 1), dtype="float32")

    for y in np.arange(kH // 2, iH - kH // 2):
        for x in np.arange(kW // 2, iW - kW // 2):
            roi = image[y - kH // 2 : y + kH // 2 + 1, x - kW // 2 : x + kW // 2 + 1]

            k = (roi * kernel).sum()
            output[y - kH // 2, x - kW // 2] = k

    return output

image_prewitt_x = convolve(image_gray, prewitt_x)
image_prewitt_y = convolve(image_gray, prewitt_y)
image_prewitt = np.sqrt(np.square(image_prewitt_x) + np.square(image_prewitt_y))

image_sobel_x = convolve(image_gray, sobel_x)
image_sobel_y = convolve(image_gray, sobel_y)
image_sobel = np.sqrt(np.square(image_sobel_x) + np.square(image_sobel_y))

image_prewitt = (image_prewitt - np.min(image_prewitt)) / (np.max(image_prewitt) - np.min(image_prewitt))

image_sobel = (image_sobel - np.min(image_sobel)) / (np.max(image_sobel) - np.min(image_sobel))

plt.subplot(2, 2, 1)
plt.imshow(image_gray, cmap='gray')
plt.title('Input Image')
plt.xticks([]), plt.yticks([])

plt.subplot(2, 2, 2)
plt.imshow(image_prewitt_x, cmap='gray')
plt.title('Prewitt X')
plt.xticks([]), plt.yticks([])

plt.subplot(2, 2, 3)
plt.imshow(image_prewitt_y, cmap='gray')
plt.title('Prewitt Y')
plt.xticks([]), plt.yticks([])

plt.subplot(2, 2, 4)
plt.imshow(image_prewitt, cmap='gray')
plt.title('Prewitt Combined')
plt.xticks([]), plt.yticks([])

plt.figure()

plt.subplot(2, 2, 1)
plt.imshow(image_gray, cmap='gray')
plt.title('Input Image')
plt.xticks([]), plt.yticks([])

plt.subplot(2, 2, 2)
plt.imshow(image_sobel_x, cmap='gray')
plt.title('Sobel X')
plt.xticks([]), plt.yticks([])

plt.subplot(2, 2, 3)
plt.imshow(image_sobel_y, cmap='gray')
plt.title('Sobel Y')
plt.xticks([]), plt.yticks([])

plt.subplot(2, 2, 4)
plt.imshow(image_sobel, cmap='gray')
plt.title('Sobel Combined')
plt.xticks([]), plt.yticks([])

plt.show()

